### ISSUE TITLE
kmcos

### ISSUE THREAD

**Issue by KS-spec** [m-deimel/CO_hydrogenation#2]
Dear Dr. Martin Deimel

Hello,
I have a question. I think there is a kmcos that supports Python 3, but why was kmos used in the paper?
Also, is there any code available to perform the same calculations using kmcos?
I would appreciate your guidance.

Thank you very much.
Best,

**Comment by m-deimel** [comment]
Hello,
yes, kmcos is essentially the port of kmos from Python 2 to Python 3.
The reason we used kmos is that the project started before this port.
In general, the same code should run with both packages except for the differences between Python 2 and Python 3.
