### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by KS-spec** [m-deimel/CO_hydrogenation#3]
Dear Dr. Martin Deimel

Hello,
I have two questions. I apologize for asking multiple times.
(1) I believe that solving a system of linear equations is necessary to obtain the nearest neighbor interactions using the cluster expansion method. Is there a python script available for this purpose? 
(2) Would tools be necessary, for example, when calculating using kmcos? And how would they be used?
Best,

**Comment by m-deimel** [comment]
Hello,
yes, to obtain the interaction energies one needs to solve a set of linear equations. However, there is no python script available.
Kmcos is quite flexible. There are no tools necessary to include lateral interactions. Depending on the backend and the use case, the determined interaction energies need to be included in the rate_constant (local_smart, lat_int) or the otf_rate (otf) expressions.
